from datetime import datetime
from app.extensions import db
from app.models.invoice import Invoice
from app.models.order import Order
from app.schemas.invoice_schema import InvoiceSchema

invoice_schema = InvoiceSchema()
invoices_schema = InvoiceSchema(many=True)

class InvoiceService:
    @staticmethod
    def generate_invoice(store_id, order_id, customer_name, customer_document=None):
        """Generate a new invoice for an order"""
        # Check if invoice already exists
        existing = Invoice.query.filter_by(order_id=order_id).first()
        if existing:
            return invoice_schema.dump(existing)
            
        order = Order.query.get(order_id)
        if not order:
            raise ValueError("El pedido asociado no existe.")
            
        # Generate sequence number per store
        invoice_count = Invoice.query.filter_by(store_id=store_id).count()
        sequence = invoice_count + 1
        invoice_number = f"FAC-{store_id}-{sequence:05d}"
        
        # Calculate subtotal, tax, total
        # Assume tax is 0 by default, subtotal is total_price
        total = order.total_price
        subtotal = total
        tax = 0.0
        
        # Payment method from order or default to 'OTRO'
        payment_method = order.payment_method or 'EFECTIVO'
        
        invoice = Invoice(
            store_id=store_id,
            order_id=order_id,
            invoice_number=invoice_number,
            customer_name=customer_name or order.customer_name,
            customer_document=customer_document,
            subtotal=subtotal,
            tax=tax,
            total=total,
            payment_method=payment_method,
            created_at=datetime.utcnow()
        )
        
        db.session.add(invoice)
        db.session.commit()
        return invoice_schema.dump(invoice)

    @staticmethod
    def get_invoice_by_order(order_id):
        """Get invoice details associated with an order"""
        invoice = Invoice.query.filter_by(order_id=order_id).first()
        if not invoice:
            return None
        return invoice_schema.dump(invoice)

    @staticmethod
    def get_invoices_by_store(store_id):
        """Get list of invoices generated by a store, newest first"""
        invoices = Invoice.query.filter_by(store_id=store_id).order_by(Invoice.created_at.desc()).all()
        return invoices_schema.dump(invoices)

    @staticmethod
    def get_invoice_details(invoice_id):
        """Get full details of a specific invoice"""
        invoice = Invoice.query.get(invoice_id)
        if not invoice:
            return None
        return invoice_schema.dump(invoice)
