version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: eshop_api_prod
    restart: always
    environment:
      # Ahora usa directamente lo que hay en el archivo .env del servidor
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FLASK_ENV: production
    networks:
      - eshop_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eshop_frontend_prod
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - eshop_network

networks:
  eshop_network:
    driver: bridge