"""add_unified_stock_and_cash_register

Revision ID: f7bbaa8a7a48
Revises: f1a2b3c4d5e6
Create Date: 2026-07-13 19:55:03.806281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bbaa8a7a48'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_register_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('opened_by_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('closing_balance_real', sa.Float(), nullable=True),
    sa.Column('closing_balance_expected', sa.Float(), nullable=True),
    sa.Column('cash_sales', sa.Float(), nullable=False),
    sa.Column('card_sales', sa.Float(), nullable=False),
    sa.Column('transfer_sales', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_document', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=20), nullable=False, server_default='WEB'))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cash_register_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_orders_cash_register_session', 'cash_register_sessions', ['cash_register_session_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_cash_register_session', type_='foreignkey')
        batch_op.drop_column('cash_register_session_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('origin')

    op.drop_table('invoices')
    op.drop_table('cash_register_sessions')
    # ### end Alembic commands ###
